/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "fixture.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CommandMessage, CommandMessage, AUTO)


PB_BIND(CommandMessage_WifiConfig, CommandMessage_WifiConfig, AUTO)


PB_BIND(CommandMessage_WifiConfig_StaticIpConfig, CommandMessage_WifiConfig_StaticIpConfig, AUTO)


PB_BIND(CommandMessage_Empty, CommandMessage_Empty, AUTO)


PB_BIND(CommandMessage_GetAttributeValue, CommandMessage_GetAttributeValue, AUTO)


PB_BIND(CommandMessage_GetAttributeValues, CommandMessage_GetAttributeValues, AUTO)


PB_BIND(CommandMessage_SetAttributeValue, CommandMessage_SetAttributeValue, AUTO)


PB_BIND(CommandMessage_SetAttributeValues, CommandMessage_SetAttributeValues, AUTO)


PB_BIND(ResponseMessage, ResponseMessage, AUTO)


PB_BIND(ResponseMessage_SetConfigResponse, ResponseMessage_SetConfigResponse, AUTO)


PB_BIND(ResponseMessage_InfoResponse, ResponseMessage_InfoResponse, AUTO)


PB_BIND(ResponseMessage_StatusResponse, ResponseMessage_StatusResponse, AUTO)


PB_BIND(ResponseMessage_HandshakeResponse, ResponseMessage_HandshakeResponse, AUTO)


PB_BIND(ResponseMessage_FixtureDefinitionResponse, ResponseMessage_FixtureDefinitionResponse, AUTO)


PB_BIND(ResponseMessage_AttributeValues, ResponseMessage_AttributeValues, AUTO)


PB_BIND(AttributeValue, AttributeValue, AUTO)


PB_BIND(SemVer, SemVer, AUTO)





